#%RAML 1.0
title: Employee
version: 1.0
baseUri: https://mocksvc.mulesoft.com/mocks/a0ce4dcc-d411-473e-97c3-ec5970ed9f73 # baseUri: https://mocksvc.mulesoft.com/mocks/ee72bf62-0d13-4643-a351-d4b6fefca8b0 # baseUri: https://mocksvc.mulesoft.com/mocks/858f9234-12d9-43ca-a734-fbfbc8a764d9 # baseUri: /
securitySchemes:
  basic:
    description: Basic authentication for API requests
    type: Basic Authentication
securedBy: basic
protocols: [HTTP, HTTPS]
mediaType: application/json
description: Query AD users
documentation:
 - title: Employee API
   content: |
     This api allows to retrive users from NEXTDC On-Premise AD.
traits:
   common-errors-trait: !include local-resources/traits/common-errors.yaml     
uses:
  empdt: local-resources/data-type/employee-datatype.raml
/v1:
 post:
  is:  [common-errors-trait]
  description: Retrive NextDc users of type employee, external, deactivated users
  body: 
    application/json:
      type: empdt.UserRequest
  responses: 
    200:
      body: 
        application/json:
          type: empdt.UserResponse
          example: !include local-resources/examples/Employee.json